modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="vihanitysfirstmod"
version="1.0"
displayName="vihanitysfirstmod"
credits="The Credit to this mod goes to Vihanity."
authors="Vihanity"
description='''
Dear Diary,
Today im gonna make a mod.
Basically an mc mod
Im trying to learn modding and stuff
but its kinda hard
but I already have some knowledge on java
so it shouldn't be that difficult
the tutorial that im watching is teaching as you don't know anything on java
ok
so thats it
bye
see ya
next mod
maybe?
yeah sure
stop going to the bottom
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
